---
title: "lefse_conda"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(MicrobiomeBenchmarkDataLefse)
library(purrr)
library(dplyr)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}
colNames <- c(
    "feature", "log", "class", "lda", "p-value" 
)
dirName <- system.file(
    "extdata", package = "MicrobiomeBenchmarkDataLefse"
)
fNames <- list.files(
    path = dirName, full.names = TRUE, pattern = ".res"
)
dats <- map(fnames, ~ read_tsv(.x, show_col_types = FALSE, col_names = colNames))
names(dats) <- str_remove(str_extract(fNames, "_a.+_w.+_lda\\d_it\\d+_bp\\d+"), "^_")
```

## Results with 0.05 p-value thr and lda 2 thr

```{r}
res <- map(dats, drop_na)
map(res, dim)
```

```{r, warning=FALSE}
dats[[1]] |>
    mutate(`p-value` = as.double(`p-value`)) |>
    filter(!is.na(`p-value`)) |> 
    mutate(pass = ifelse(`p-value` < 0.01, "yes", "no")) |> 
    pull(pass) |> 
    table()
```


```{r}
sessioninfo::session_info()
```
